#!/bin/sh

#start-pulseaudio-x11 &
#eval "$(dbus-launch --sh-syntax --exit-with-session)"
#XCURSOR_THEME=DMZBlackLH
#xinput set-button-map 9 3 2 1
#xinput set-prop 9 'libinput Accel Speed' -0.3

run_dwm() {
	#xsetroot -solid "#333333"
	xrdb $HOME/.Xresources
	feh --randomize \
		--bg-scale $HOME/Pictures/Wallpapers/Landscape/*.jpg \
		--bg-scale $HOME/Pictures/Wallpapers/Portrait/*.jpg
	xsidle.sh slock &
	dwm_update_status.sh 2>&1 >/dev/null &
	#fcitx &
	exec dwm
}

run_bspwm() {
	xrdb $HOME/.Xresources
	feh --randomize \
		--bg-scale $HOME/Pictures/Wallpapers/Landscape/*.jpg \
		--bg-scale $HOME/Pictures/Wallpapers/Portrait/*.jpg
	sxhkd &
	exec bspwm
}

run_2bwm() {
	xrdb $HOME/.Xresources
	feh --randomize \
		--bg-scale $HOME/Pictures/Wallpapers/Landscape/*.jpg \
		--bg-scale $HOME/Pictures/Wallpapers/Portrait/*.jpg
	#setxkbmap us dvp
	#setxkbmap -layout us -variant dvp -option compose:102 -option numpad:shift3 -option kpdl:semi -option keypad:atm -option caps:shift
	~/.local/bin/lemon2bstatus.sh &
	exec 2bwm

}

run_sowm() {
	xrdb $HOME/.Xresources
	feh --randomize \
		--bg-scale $HOME/Pictures/Wallpapers/Landscape/*.jpg \
		--bg-scale $HOME/Pictures/Wallpapers/Portrait/*.jpg
	exec sowm
}

run_exwm() {
	#xhost +SI:localuser:$USER
	xsetroot -cursor_name left_ptr
	xset r rate 200 60
	exec emacs -q --load $HOME/Downloads/init.el
}

run_tinywm() {
	xrdb $HOME/.Xresources
	feh --randomize \
		--bg-scale $HOME/Pictures/Wallpapers/Landscape/*.jpg \
		--bg-scale $HOME/Pictures/Wallpapers/Portrait/*.jpg
	st &
	exec tinywm
}

run_i3() {
	exec i3
}

export SESSION=${1:-dwm}

case $SESSION in
	dwm )		run_dwm;;
	bspwm )		run_bspwm;;
	openbox )	exec openbox-session;;
	lxqt )		exec startlxqt;;
	xmonad )	exec xmonad;;
	xfce )		exec startxfce4;;
	budgie )	exec budgie-desktop;;
	gnome )		exec gnome-session;;
	i3 )		exec run_i3;;
	2bwm )		run_2bwm;;
	sowm )		run_sowm;;
	exwm )		run_exwm;;
	tinywm )	run_tinywm;;
	* )		exec $SESSION;;
esac
